version: '3.8'

services:
  feature_pipeline:
    image: my_ml_image
    container_name: feature_pipeline
    volumes:
      - ./src/features:/app
    command: python3 feature_pipeline.py

  training_pipeline:
    image: my_ml_image
    container_name: training_pipeline
    volumes:
      - ./src/features:/app
    command: python3 train_pipeline.py

  inference:
    image: my_ml_image
    container_name: inference
    volumes:
      - ./src/features:/app
    command: python3 inference_pipeline.py

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: requirements.txt
    container_name: fastapi_app
    ports:
      - "8085:8000"
    command: ["uvicorn", "api.fast_api:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - hops

  hops:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTS_FILE: requirements_hops.txt
    container_name: hops_app
    ports:
      - "5000:5000"