name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install hops dependencies
        run: |
          pip install -r requirements_hops.txt

      - name: Run tests
        run: |
          pytest test/ --maxfail=1 --disable-warnings -q

      - name: Run linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Run Docker Compose
        run: |
          docker-compose up -d
          sleep 10

      - name: Test FastAPI health endpoint
        run: |
          curl --fail http://localhost:8085/docs || exit 1

      - name: Tear down
        if: always()
        run: docker-compose down
