name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install hops dependencies
        run: pip install -r requirements_hops.txt

      - name: Run tests
        run: pytest test/ --maxfail=1 --disable-warnings -q

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build Docker images
        run: docker compose -f docker-compose.yaml build --no-cache

      # Sequential pipeline execution
      - name: Run feature pipeline
        run: docker compose -f docker-compose.yaml up feature_pipeline

      - name: Start MLflow service
        run: |
          docker compose -f docker-compose.yaml up -d mlflow
          echo "Waiting for MLflow to be ready..."
          until curl -s http://localhost:5000 > /dev/null 2>&1; do
            sleep 2
            echo "Waiting..."
          done
          echo "MLflow is up!"

      - name: Run training pipeline
        run: docker compose -f docker-compose.yaml up training_pipeline

      - name: Run inference pipeline
        run: docker compose -f docker-compose.yaml up inference

      - name: Start FastAPI
        run: docker compose -f docker-compose.yaml up -d fastapi

      - name: Wait for FastAPI to be ready
        run: |
          echo "Waiting for FastAPI..."
          SECONDS=0
          until curl -s http://fastapi:8000/docs > /dev/null 2>&1; do
            sleep 2
            echo "Waiting..."
            if [ $SECONDS -gt 60 ]; then
                echo "Timeout: FastAPI did not start in 60s"
                exit 1
            fi
          done
          echo "FastAPI is up!"

      - name: Test FastAPI health endpoint
        run: curl --fail http://fastapi:8000/docs || exit 1

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yaml down
